version: 3.7
services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
     environment:
        - MONGO_INITDB_ROOT_USERNAME: 'user'
        - MONGO_INITDB_ROOT_PASSWORD: 'password'
    restart: always


    node-todo:
        build: .
        container_name: node-todo
        hostname: node-todo
        ports:
        - 80:8080/tcp
        tty: true
        links:
       	- mongodb
        depends_on:
        - mongodb


